# DATABASE
MYSQL_HOST: 172.29.144.1
MYSQL_PORT: 3306
MYSQL_DATABASE: recouvrement
MYSQL_USERNAME: root
MYSQL_PASSWORD: testpassword123

# SERVER CONFIG
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

# EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: aaronborgi1@gmail.com
EMAIL_PASSWORD: ktsyqilgtvxncuxv

# JWT
JWT_SECRET: 59337C795F2EE06CB3547DA63ECC77E7E0C5DF9715C94F72C3D844EECD19F169

# UI APP URL
UI_APP_URL: http://172.29.144.1